# Generated by Django 3.0.6 on 2020-05-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Food', 'Food'), ('People', 'People'), ('Travel', 'Travel'), ('Architecture', 'Architecture')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(choices=[('Nairobi', 'Kenya'), ('Kuala Lumpur', 'Malaysia'), ('Cape Town', 'South Africa')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Location')),
            ],
        ),
    ]
